{{- if .Values.luckperms.enabled }}
{{- $mariadbPassword := randAlphaNum 32 }}
apiVersion: v1
kind: Secret
metadata:
  name: lp-mariadb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ $mariadbPassword | b64enc | quote }}
stringData:
  MARIADB_URI: "mysql://root:{{ $mariadbPassword }}@lp-mariadb-service:3306/luckperms"
{{- end }}
