{{- if .Values.luckperms.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  {{- if .Values.luckperms.mariadb.storage.volumeName }}
  volumeName: {{ .Values.luckperms.mariadb.storage.volumeName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.luckperms.mariadb.storage.size }}
{{- end }}
