{{- if .Values.luckperms.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: lp-mariadb-service
spec:
  selector:
    app: lp-mariadb
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: {{ .Values.luckperms.mariadb.port }}
      protocol: TCP
  type: NodePort
{{- end }}
