{{- if .Values.luckperms.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lp-mariadb
spec:
  serviceName: lp-mariadb-service
  replicas: 1
  selector:
    matchLabels:
      app: lp-mariadb
  template:
    metadata:
      labels:
        app: lp-mariadb
    spec:
      volumes:
        - name: lp-mariadb-data
          persistentVolumeClaim:
            claimName: lp-mariadb-pvc
      containers:
        - name: lp-mariadb
          image: mariadb:11.8
          ports:
            - containerPort: 3306
              name: lp-mariadb
          envFrom:
            - secretRef:
                name: lp-mariadb-secret
            - configMapRef:
                name: lp-mariadb-config
          volumeMounts:
            - name: lp-mariadb-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
{{- end }}
