mongodb:
  port:
  storage:
    volumeName:
    size: 512Mi

redis:
  port:
  storage:
    volumeName:
    size: 256Mi

luckperms:
  enabled: true
  mariadb:
    port:
    storage:
      volumeName:
      size: 512Mi